---
engines:
 pylint:
   enabled: true
   python_version: 3
    
 duplication:
   enabled: true

 metrics:
   enabled: true

 coverage:
   enabled: true

languages:
   python:

exclude_paths:
- tests/*
- setup.py
