name: Release

on:
  push:
    tags:
      - 'v*.*.*'      # e.g., v0.6.0, v0.6.1
      - 'v*.*.*rc*'   # prereleases like v0.7.0rc1
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so hatch-vcs can see tags
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install deps
        run: uv pip install -e ".[dev]"
      - name: Unit tests
        run: uv run pytest -q

  publish-testpypi:
    needs: build-test
    runs-on: ubuntu-latest
    environment: testpypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Build dist
        run: uv build --sdist --wheel
      - name: Publish to TestPyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: uv publish --index testpypi --token "$UV_PUBLISH_TOKEN"

  promote-pypi:
    needs: publish-testpypi
    runs-on: ubuntu-latest
    environment: pypi   # protect with approvals in GitHub Environments
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Build dist (repeat for safety)
        run: uv build --sdist --wheel
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token "$UV_PUBLISH_TOKEN"
